# Web Server VM Template
# Optimized for web applications with adequate resources

web-server:
  vcpus: 2
  memory_mb: 1024
  kernel: "images/linux/vmlinux.bin"
  rootfs: "images/linux/web-server-rootfs.ext4"
  boot_args: "console=ttyS0 reboot=k panic=1 root=/dev/vda rw"
  network_config:
    bridge: "chbr0"
    dhcp: true
  guest_agent:
    enabled: true
    port: 8080
  storage:
    additional_disks: []
  resource_limits:
    cpu_quota_percent: 80
    memory_limit_percent: 90
  packages:
    - nginx
    - nodejs
    - npm
    - curl
    - htop
  description: "Template for web server applications with Node.js and Nginx"